sudo: true
language: python
python:
    - "2.7"
    - "3.6"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq pandoc

install: pip install -r requirements-dev.txt

script:
- ./download-models.sh
- tox
- tox -e flake8

after_success:
- tox -e coverage-report
- codecov
